/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentAlert: typeof import('./components/content/ContentAlert.vue')['default']
    ContentCodeTab: typeof import('./components/content/ContentCodeTab.vue')['default']
    ContentHelp: typeof import('./components/content/ContentHelp.vue')['default']
    ContentHowToButton: typeof import('./components/content/ContentHowToButton.vue')['default']
    ContentNavigation: typeof import('./components/content/ContentNavigation.vue')['default']
    D3AdjacencyList: typeof import('./components/d3/D3AdjacencyList.vue')['default']
    D3AdjacencyMatrix: typeof import('./components/d3/D3AdjacencyMatrix.vue')['default']
    D3AlgorithmControl: typeof import('./components/d3/D3AlgorithmControl.vue')['default']
    D3AlgorithmResult: typeof import('./components/d3/D3AlgorithmResult.vue')['default']
    D3EdgeList: typeof import('./components/d3/D3EdgeList.vue')['default']
    D3Svg: typeof import('./components/d3/D3Svg.vue')['default']
    D3SvgDropdownHint: typeof import('./components/d3/D3SvgDropdownHint.vue')['default']
    ProseH2: typeof import('./components/content/ProseH2.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavbar: typeof import('./components/TheNavbar.vue')['default']
  }
}
